### ISSUE TITLE
"Easy" isn't so easy for a newbie.

### ISSUE THREAD

**Issue by JDRay42** [ALMMa/datatables.aspnet#15]
My issue isn't with the quality of the code, which I can't assess, but with the documentation.  The instructions say, in essence, "piece of cake, see?"  But for someone who's entirely new to MVC, there are (potentially) steps missing.  Download project, compile, add reference to assembly?  Add "using ..." somewhere?  I see there's a NuGet package.  Once I add it to the project, then what?

Sorry for the n00b questions.  I only offer that improving documentation will improve usability.

**Comment by scottheckel** [comment]
Here's a basic outline assuming you already know how to use jQuery DataTables.

1) Install the NuGet package.
2) Make a controller action that looks something like the following:
```
public async Task<ActionResult> MyAction([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel) {
    // From here use requestModel to run your search

    // Return search requests assuming you populated these variables above
    return Json(new DataTablesResponse(requestModel.Draw, results, totalFilteredRecords, totalRecords);
}
```
3) Client-side use datatables to retrieve results from Controller.MyAction

**Comment by JDRay42** [comment]
Thanks.  This is a start at least.  However, after downloading the NuGet package (I searched for datatables.mvc, found only one, installed it) and pasting in your code (btw, you're missing a ')' at the end of the `return` statement), I'm getting a lot of "Type or namespace could not be found" errors.  I added `using JQueryDataTablesForMVC;`, but that didn't help.  What am I missing?

**Comment by scottheckel** [comment]
Oh, shoot. I forgot I'm not using Nuget for this.  Replace #1 with this.

I downloaded the project from on here and put it as another project in my solution. After you add the project to your solution, you want to add a reference to your local project for it. 

The other option would be to build a DLL of the project and include the reference to that dll.

This project is pretty dead... it would be nice for someone to fork this, start a nuget, and update the documentation.

**Comment by JDRay42** [comment]
I found a different NuGet package (DataTables.MVC5) that lists Anderson Luiz Mendes Matos as one of the authors.  I replaced the other one with this one, and things are working better.  Now just to implementing the guts of the ActionResult.

**Comment by JDRay42** [comment]
Here's what I came up with:
```
        public ActionResult Index([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel)
        {
            // From here use requestModel to run your search
            return View(new DataTablesResponse(requestModel.Draw, db.Products.ToList(), 0, db.Products.ToList().Count));
        }
```

Obviously I've modified `public async Task<ActionResult>` to simply `public ActionResult`, which should (fingers crossed) suffice for my needs.  At any rate, it mirrors the other methods in the controller.  And it builds, which is a bonus.  I haven't tried it yet, though...

**Comment by ALMMa** [comment]
Marked as duplicate: samples will be provided starting with version 2.0.
