### ISSUE TITLE
Announcing the rebirth of DataTables.Mvc (version 2.0.0-alpha-1)

### ISSUE THREAD

**Issue by ALMMa** [ALMMa/datatables.aspnet#18]
Hello all.

When I first wrote DataTables.Mvc code, it was meant to be a toolkit to help users on their existing projects, not a full out-of-the-box solution for DataTables to work with Asp.Net MVC.

In fact, it was more of an abstraction to prevent your code to directly access DataTables parameters and all, not only helping you avoid parameter handling but also prevent external code (my code) into your all, leaving all logic (filter, sort, etc) to you.

After released, we all started using DataTables.Mvc and it has grown a bit. Problem is that when this project was made, it came from an internal project from my company and because of that, code evolution was a bit tied up to that cycle.

As of june/2015, we decided to review our projects and more even more use of DataTables into our projects, to avoid external (paid) grid components.

Since our projects are now Asp.Net 5, DataGrid.Mvc has to be fully rewritten to not only provide all necessary features (as requested by many users) but also to include tests, samples and to become a full out-of-the-box framework to work with DataTables within Asp.Net MVC and WebAPI.

Not only that: we will release official NuGet packages for DataTables.Mvc core and ORM modules, starting with Dapper (each module will have it's helpers to deal with sorting, filtering and more).

First release (2.0.0-alpha-1) is planned by the end of june.

If you have any comments and suggestions, please, share them here so I can plan a better DataTables.Mvc for us all 

=)

**Comment by scottheckel** [comment]
Great news! I have an internal version of this myself from the previous release of VS 2015. Any idea when you'll start to throw this on GitHub, so we can help contribute back? I don't see anything out there right now.

**Comment by ALMMa** [comment]
Hey Scott!


As of today, we're performing a major review of needs and goals for the project from within my company. Simply put: we're creating an initial backlog.

Starting 11/jun I'll perform a wire-up to consolidate existing code as "1.2", tag it, move from stable to legacy, empty stable branch and create a new dev branch (which will be used instead). Git Workflow will be used to organize versions. This should all be ready on the same day.

Directives and first docs should appear also on 11/jun, with techs we plan to use, links to legacy version, directives to contribute, conventions and all.

First commit should appear as soon as 22~23/jun.
It will have what we think of a modular system to help attach DataTables into various projects, including WebApi and MVC, including a modular system for helpers (starting with Dapper/DapperExtensions).

Most likely we will have 2~3 projects to use DataTables on a single solution. The ideia is similar to the Identity framework for Asp.Net: get only what you need.

A wiki will be released with samples and tutorials along with code and I'll create a landing page for the project ASAP (probably 27~28/jun).
=)

Contributors are more than welcome.
Stay tuned =)

**Comment by ALMMa** [comment]
Sorry I'm a bit late.

Initial commit is ready, along with some very very basic integration samples.
My ideia is to create around 10~15 samples with usage, helpers, extensions, custom options and all, so newbies will find it easier to understand.

I just have to export nuget and publish them. Will be ready to test in a couple hours.
Hope you all enjoy this =)
