### ISSUE TITLE
AditionaParameters

### ISSUE THREAD

**Issue by diam0nds** [ALMMa/datatables.aspnet#19]
First of all congratulations for the project (Great work!!!) and sorry for my bad English .

I am a complete newbie in the world of web programming and I cannot understand how to use AditionalParameters to handle custom values ​​to be passed to the request .

It's possible to have clarification on this argument?
thanks

**Comment by ALMMa** [comment]
@diam0nds, Thanks.

First, you need to send those parameters using jQuery DataTables. For that, check DT help:
https://www.datatables.net/examples/server_side/custom_vars.html

After that, those parameters will get lost unless you specifically enable AND handle them. That's necessary to increase performance when not using aditional parameters and to help prevent parsing content that might break your app (AKA: attacks).

Considering you're using DataTables.AspNet.Mvc reference, you should do:

```csharp
// Global.asax > on method Application_Startup()
DataTables.AspNet.Mvc5.Configuration.Register(MyParseFunction, true);
// Remember that the last parameter ('true') enables aditional response parameters. If you don't need them (only request parameters), keep it false.
```

Also, you'll need your custom parameter parser. I've used the name 'MyParseFunction'. Here's a sample:

```csharp
// Parses custom parameters sent with the request.
public IDictionary<string, object> MyParseFunction(ControllerContext controllerContext, ModelBindingContext bindingContext)
{
   var values = new Dictionary<string, object>();

   var sampleParameter = bindingContext.ValueProvider.GetValue("_just_my_custom_http_value");
   values.Add("sampleValue", sampleParameter.RawValue);

   return values;
}
```
