### ISSUE TITLE
Provide sample projects

### ISSUE THREAD

**Issue by ALMMa** [ALMMa/datatables.aspnet#2]
Provide samples using:
- LinqToEntities (Entity Framework)
- DynamicLinq (in-memory collections)
- Dapper.net

**Comment by rodrigoporcionato** [comment]
This project is active?
I need some sample to use in MVC 5 with Ajax call.

**Comment by rezalesmana** [comment]
Hi, guys... I've been able to handle sorting and paging using this library. 

For sorting you need to do these steps :

1. Set the sorting options on the javascript. However, I'm unable to use "order" option ( https://datatables.net/examples/basic_init/table_sorting.html ) - no clue why. But, I manage to use the legacy option "aaSorting" ( http://legacy.datatables.net/ref ).

2. After the javascript setting, you need to get the sortedColumns on the server (using DefaultDataTablesRequest.Columns.GetSortedColumns() method). SortedColumns is a list of Column which will have the sorting direction. 

Snippet code : 

https://gist.github.com/rezalesmana/5a482b357dcb8217e8e5

Please contact me if you need more... :)

**Comment by ALMMa** [comment]
Hello guys,

Project is alive, but not so active (for now).

Apart from some health problems on past months, now I'm facing a full
rewrite of softwares due to some legal changes.
So, for the next couple of months I can't guarantee much new work here.
Sorry, really.

I had to stop about everything else to focus on these internal projects.

Merge requests are always welcome!
As any other project on GitHub, you can adapt, suggest and improve this
project and request a merge.
That's fast enough for me to track and accept/reject and everyone can
benefit from that
=)


When all this fuzz here is done, I'll be back with not only better coding
but a full test suite, full MVC samples, WebAPI samples, AspNet5
compatibility (and samples) and (finally!) NuGet packs.


[]'s

*Anderson Luiz Mendes Matos*
MBA IT Governance and Software Engineering
Microsoft .NET technology leader
CIO Nacional Soft
*www.andersonmatos.com.br <http://www.andersonmatos.com.br>*

2015-03-06 2:06 GMT-03:00 Reza Lesmana <notifications@github.com>:

**Comment by ALMMa** [comment]
First sample projects include very very basic integration (only default config and no extense use).
They provide some initial guidance on integration with both MVC5 and AspNet5.

Check them on 'dev' branch.

More samples will follow soon.
