### ISSUE TITLE
Doesn't work with ASP.NET 5 RC1

### ISSUE THREAD

**Issue by ghrapan** [ALMMa/datatables.aspnet#25]
Please upgrade DataTables.AspNet.AspNet5 to use ASP.NET 5 RC1 instead of beta8.

Thanks!

**Comment by ALMMa** [comment]
Already working on it, should be finished within the next couple days.
Sorry about the delay :)

**Comment by ALMMa** [comment]
Fixed within yesterday's commit - check Beta2 on NuGet.
