### ISSUE TITLE
The value of the search cannot be null. If there's no search performed, provide an empty string

### ISSUE THREAD

**Issue by Pooik** [ALMMa/datatables.aspnet#27]
Hi,
When I load data, I get error 500 with: "_The value of the search cannot be null. If there's no search performed, provide an empty string_."

But I do not use search. My javascript is like this:
$('#table').DataTable({
    'serverSide': true,
    'processing': true,
    'filter': false,
    'ajax': '/webserviceurl',
    'columns': [
        { 'data': 'id' },
        { 'data': 'name' }
    ]
});

I can see there is a validation in the constructor of Search class but have no idea from where it is called and why the passed value is null.

**Setting filer: true/false have no effect, throws error everytime.**

**Comment by ALMMa** [comment]
Can you please specify whith DataTables version you're using (current: 1.10.11)?
This way I can simulate the same environment and fix this issue :)

**Comment by Pooik** [comment]
Hi,

sure. I'm using DataTables 1.10.9-dev (it¨s a bought template which I'm implementing into ASP.NET MVC). If you think this could be an isssue, let me know. Will try to update. (hope does not break anything).
Thanks

**Comment by ALMMa** [comment]
Closed: inactive.
