### ISSUE TITLE
ModelBinder should not break on name

### ISSUE THREAD

**Issue by LeandroPT** [ALMMa/datatables.aspnet#28]
Model parser fails to parse if either name or data is not set.

`// Parses Name value.`
`var columnName = values.GetValue(String.Format(names.ColumnName, counter));`
`string _columnName = null;`
`if (!Parse<string>(columnName, out _columnName)) break;`

I think that if name is not set, it should be the same as data.

**Comment by skorunka** [comment]
Yes, "name" should not be mandatory. If not set, keep it null: https://github.com/ALMMa/datatables.aspnet/pull/43
