### ISSUE TITLE
Breaks on ASP.Net Core RC2

### ISSUE THREAD

**Issue by tedd** [ALMMa/datatables.aspnet#30]
Used on ASP.Net RC1, worked great. On ASP.Net RC2 it doesn't work, it tries to pull in RC1 which causes problems in the project. Probably simple to fix, wasn't too hard to upgrade my project from RC1 to RC2.

**Comment by ALMMa** [comment]
Duplicate. RC2 is a work in progress but should take a few days to be ready.
Check this issue for more info: https://github.com/ALMMa/datatables.aspnet/issues/29
