### ISSUE TITLE
Unable to override SerializeData in DataTablesResponse

### ISSUE THREAD

**Issue by bogusz** [ALMMa/datatables.aspnet#31]
Hi,

I would like to change the serialization settings in DataTablesResponse. You even have a comment on SerializeData method that: " Can be overriten when needed.". But actually it can't because all the constructors are private so DataTablesResponse can't be inherited. It's probably something to fix :)

Cheers,
Bogusz

**Comment by ALMMa** [comment]
Just checked that. Will be fixed on next release (2.0.1).

**Comment by Manu-LT** [comment]
Omg, btw good work and thank you for sharing.
