### ISSUE TITLE
vs 2013 solution for mvc5 and webapi2

### ISSUE THREAD

**Issue by c-arnab** [ALMMa/datatables.aspnet#38]
It would be great if a vs 2013 solution could be provided of the latest stable version

**Comment by ALMMa** [comment]
Currently there are no plans to support VS 2013 since it's an older version of the IDE and because .NET Core is recommended on VS 2015 and not on VS 2013.
Why do you need a VS 2013 solution (sln) file?

**Comment by c-arnab** [comment]
I got VS 2015, changed the global.json to match my version, went to manage nuget packages and clicked in restore.Even after that on build gives 1500-2000 errors, while checking found that all project.json dependencies show could not resolve.
Then went to a specific project and selected dotnet restore on that found the error below..

Error reading 'D:\xxx\project.json' at line 10 column 30 : Package dependencies must specify a version r
ange.

**Comment by ALMMa** [comment]
What is the version you have set on global.json?
