### ISSUE TITLE
MissingMethodException: Cannot create an instance of an interface

### ISSUE THREAD

**Issue by Lann094** [ALMMa/datatables.aspnet#39]
Hi,

I apologise if this is a simple fix, but I'm quite new to this kind of MVC workflow, and I'm completely stumped on what to do next.

I'm trying to set up a datatable that will allow POSTing, and this library seemed the best method, along with performing filtering of a large amount of data server-side. I've more or less replicated the MVC5 example, but I keep getting the exception in title when doing the AJAX query to get the table data. Do you have any pointers on what I might be able to do to resolve this? My PageData ActionResult, and javascript code for initialising the table are the same as the example, it's just my data that's different, which is via Entity Framework.

Thanks in advance for the help, and I really do hope this isn't a dumb question...

**Comment by ALMMa** [comment]
@Lann094, there is no problem at all.
Please, take a look into issue #37 which shows the same error and it's corresponding fix.
It might help with server-side filters and sorting too.
;)
