### ISSUE TITLE
Could not create a model binder for model object of typeDataTables.AspNet.Core.IDataTablesRequest

### ISSUE THREAD

**Issue by hyuksel** [ALMMa/datatables.aspnet#42]
Hi,

is this package compatible with DotNetCore 1.1?
I've made a test project in Visual Studio 2017RC and i'm getting the following error:

 <h1>An unhandled exception occurred while processing the request.</h1>
            <div class="titleerror">InvalidOperationException: Could not create a model binder for model object of type &#x27;DataTables.AspNet.Core.IDataTablesRequest&#x27;.</div>
                <p class="location">Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinder(ModelBinderFactoryContext context)</p>

Thanks. Hayko.

**Comment by ALMMa** [comment]
Looks like it's missing the needed binders which are made available through service registration for AspNet Core on `Startup.cs`. Please, take a look into the DataTables.AspNet registration:

[Startup.cs (from samples)](https://github.com/ALMMa/datatables.aspnet/blob/master/samples/DataTables.AspNet.Samples.AspNetCore.BasicIntegration/Startup.cs)

**Comment by hyuksel** [comment]
Thanks!
