### ISSUE TITLE
How to export all row from DataTables using Server Side Processing?

### ISSUE THREAD

**Issue by Tegawende** [ALMMa/datatables.aspnet#53]
Hello,
When i use CSV or EXCEL button, the rows exported are only those which are on the current screen.
Do you know how i can fix that and get all the rows once ? 

Thx

**Comment by ALMMa** [comment]
@Tegawende this is related to the jQuery DataTables or one of it's plugins.

This GitHub repo is related to DataTables.AspNet which is a server-side .NET mapper for jQuery DataTables request/response objects, not the plugin (javascript) itself. We're not the creators of jQuery DataTables. Instead, we just provide an easier way to integrate client-side (jQuery DataTables) with server-side (with Nuget).

We offer no support for DataTables or it's plugins. You may check more about jQuery DataTables (including a possible fix for this) on their website: [https://datatables.net](https://datatables.net/)
