### ISSUE TITLE
An unhandled exception occurred while processing the request.

### ISSUE THREAD

**Issue by nutbutter** [ALMMa/datatables.aspnet#57]
When open the page, I got this:
InvalidOperationException: Could not create an instance of type 'DataTables.AspNet.Core.IDataTablesRequest'. Model bound complex types must not be abstract or value types and must have a parameterless constructor.

Please help me out.

**Comment by ALMMa** [comment]
Check out issues #42 #39 and #37 they might be of help.

**Comment by nutbutter** [comment]
Problem solved. Thank you!
