### ISSUE TITLE
WebApi2 Model Binder?

### ISSUE THREAD

**Issue by HairyOneMan** [ALMMa/datatables.aspnet#7]
First thing first: Great Work :)

I've just wanted to ask, if you'll implement WebApi2 Model Binder (It has to be System.Web.Http.ModelBinding.IModelBinder instead of System.Web.Mvc.IModelBinder). I think it's quite quick as i'm lokoing into the code. Anyway, thx for this. 

EDIT:

for me, it was enough to implement the System.Web.Http.ModelBinding with your methods, updating just the ResolveNameValueCollection to this:

```csharp
protected virtual NameValueCollection ResolveNameValueCollection(HttpRequestMessage request)
        {
            if (request.Method == HttpMethod.Get) return HttpUtility.ParseQueryString(request.RequestUri.Query);
            else if (request.Method == HttpMethod.Post)
            {
                var data = request.Content.ReadAsStringAsync().Result;
                return HttpUtility.ParseQueryString(data);
            }
            else throw new ArgumentException(String.Format("The provided HTTP method ({0}) is not a valid method to use with DataTablesBinder. Please, use HTTP GET or POST methods only.", request.Method), "method");
        }
```

**Comment by Incognito-Nemo** [comment]
Hello HairyOneMan!

I don't understand what is the object DataTablesWithAdminPropertyWebApiBinder… Could you explain more ?

Thanks a lot !

**Comment by HairyOneMan** [comment]
Hello,

it's just extended web api binder with additional property (admin flag is posted from datatables request) . Check the custom parameters section on readme of this project.

**Comment by ALMMa** [comment]
Today's commit just implemented WebApi2 support. NuGet packages are available now.
