### ISSUE TITLE
NuGet?

### ISSUE THREAD

**Issue by ChuckBryan** [ALMMa/datatables.aspnet#8]
There are lots of these on NuGet...Would you add this one too?

**Comment by dageniusal** [comment]
+1

**Comment by rezalesmana** [comment]
+1, would love it if it can be added as nuget. Already using it in a development project. :)

**Comment by fassetar** [comment]
+1

**Comment by otif11** [comment]
Anderson coloca la biblioteca en Nuget bro, seguro que las descargas aumentan considerablemente.

**Comment by davormas** [comment]
+1

**Comment by Incognito-Nemo** [comment]
+1

**Comment by digitalrizzle** [comment]
+1

**Comment by ALMMa** [comment]
NuGet will be available for DataTables.Mvc 2.0 starting with alpha-1.

**Comment by ChuckBryan** [comment]
Awesome!

**Comment by ALMMa** [comment]
First NuGet oficial package for DataTables.AspNet is available.
It's a prerelease version (alpha1) and as with any alpha/beta version, should only be used on dev/test environments.

Beta is expected in a month and stable a few weeks later.

There are 3 available packages, including:
- DataTables.AspNet.Core, which has the core elements for DataTables (interfaces, enums, etc).
- DataTables.AspNet.Mvc5, which has MVC5-compatible binders and registration.
- DataTables.AspNet.AspNet5, which has AspNet5-compatible binders and registration.

Hope you enjoy =)

**Comment by ChuckBryan** [comment]
Thank you!!! Looking forward to testing this :)
