### ISSUE TITLE
Global search doesn't work !

### ISSUE THREAD

**Issue by hello-code** [ALMMa/datatables.aspnet#9]
When global search will throw  "The value of the search cannot be null. If there's no search performed, provide an empty string."
I don't know why.But when I modify GetFilteredColumns(),that will ok.
The change is:
public IEnumerable<Column> GetFilteredColumns()
        {
            return Data.Where(_column => !String.IsNullOrWhiteSpace(_column.Data) && _column.Searchable);
        }

**Comment by ALMMa** [comment]
This will be marked as closed as DataTables is undergoing a full rewrite.
After it reaches beta I'll make sure global search works in a more predictable way.
